### ISSUE TITLE
Remove SCSS IntelliSense

### ISSUE THREAD

**Issue by amezick** [gkkirilov/scc-productivity-pack#4]
This plugin is not supported.  There have been no updates in 3 years.  There is a known issue where this plugin causes high CPU usage.

**Comment by georgiai1** [comment]
Thanks for the contribution @amezick, do you think this should be substituted with a new extension or the default behavior of VSCode is good enough?

**Comment by amezick** [comment]
It would be good to have an extension for scss but I have no suggestions.  I mostly concentrate on backend code.  I submitted this ticket because our designers noticed that the SCSS IntelliSense extension was causing very high CPU load.
Thanks!
