### ISSUE TITLE
Isml Linter Extension for VS Code

### ISSUE THREAD

**Issue by osapishchuk** [gkkirilov/scc-productivity-pack#6]
Add "Isml Linter" by "Fabiow Quixadá", link reference:

- https://github.com/FabiowQuixada/vscode-isml-linter

marketplace plugin page:

- https://marketplace.visualstudio.com/items?itemName=fabiowquixada.vscode-isml-linter

**Comment by osapishchuk** [comment]
Hi @gkkirilov, any chance to review this contribution?

**Comment by georgiai1** [comment]
Hey @Gektorian thanks for writing a second time as I missed the first, I will review it ASAP

**Comment by georgiai1** [comment]
Published version 1.0.3
